config/routes.rb
Rails.application.routes.draw do
  get '/retailers/edit/:id', :to => "retailers#edit", :as => "edit_retailer"
  get '/retailers/new', :to => "retailers#new", :as => "new_retailer"
  get '/retailers/index', :to => "retailers#index", :as => "retailer"
  patch '/retailers/update/:id', :to => "retailers#update", :as => "update_retailer"


  post '/retailers/create', :to => "retailers#create", :as => "create_retailer"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/retailer.rb
class Retailer < ApplicationRecord
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  
  def new
    @retailer = Retailer.new
  end

  def index 
    @retailers = Retailer.all
  end

  def edit
    @retailer = Retailer.find(params[:id])
  end

  def update
    @retailer = Retailer.find(params[:id])
    @retailer.update(retailer_params)
    redirect_to retailer_path
  end 

  def create
    @retailer = Retailer.new(retailer_params)
    @retailer.save
    redirect_to retailer_path
  end

  private
  def retailer_params
    params.require(:retailer).permit(:code, :shop_name, :retialer_name, :mobile_number, :address, :status)
  end
  def mobile_number
    [:mobile_number1, :mobile_number2]
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/retailers_helper.rb
module RetailersHelper
end

app/views/layouts/application.html.erb
  

<html>
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
</head>
<body>

<div class="container-fluid">
    <!-- Static navbar -->
    <nav class="navbar navbar-default">
      <div class="">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="https://www.systembyran.se" target="_blank">Systembyran</a>
        </div>


        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class=""><a href="#">Home <span class="sr-only">(current)</span></a></li>
            <li class="hideable"><a href="#">Menu item</a></li>
            <li class="hideable"><a href="#">Menu Item 2</a></li>
            <li class="hideable"><a href="#">Menu item 3</a></li>
            <li class="hideable"><a href="#">Menu item 4</a></li>
            <li class="hideable"><a href="#">Menu item 5</a></li>
            <li class="hideable"><a href="#">Menu item 6</a></li>
            
            <li id="nav-more" class="dropdown hidden"><!-- the 'more' dropdown item, originally hidden -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">MORE <span class="caret"></span></a>
              <ul class="dropdown-menu">
              </ul>
            </li>
            
            <li><a href="#"><i class="glyphicon glyphicon-globe"></i></a></li>
          </ul>
        </div>        
      </div>   
    </nav>
  </div>
 

    <div class="row profile">
    <div class="box effect">
    <div class="col-md-3">
      <div class="profile-sidebar">
        <!-- SIDEBAR USERPIC 
        <div class="profile-userpic">
          <img src="http://keenthemes.com/preview/metronic/theme/assets/admin/pages/media/profile/profile_user.jpg" class="img-responsive" alt="">
        </div> -->
        <!-- END SIDEBAR USERPIC -->
        <!-- SIDEBAR USER TITLE -->
        <div class="profile-usertitle">
          <div class="profile-usertitle-name">
            Marcus Doe
          </div>
          <div class="profile-usertitle-job">
            Developer
          </div>
        </div>
        <!-- END SIDEBAR USER TITLE -->
        <!-- SIDEBAR BUTTONS -->
        <div class="profile-userbuttons">
          <button type="button" class="btn btn-success btn-sm">Follow</button>
          <button type="button" class="btn btn-danger btn-sm">Message</button>
        </div>
        <!-- END SIDEBAR BUTTONS -->
        <!-- SIDEBAR MENU -->
        <div class="profile-usermenu">
          <ul class="nav">
            <li class="">
              <a href="#">
              <i class="glyphicon glyphicon-home"></i>
              Overview </a>
            </li>
            <li>
              <a href="#">
              <i class="glyphicon glyphicon-user"></i>
              Account Settings </a>
            </li>
            <li>
              <a href="#" target="_blank">
              <i class="glyphicon glyphicon-ok"></i>
              Tasks </a>
            </li>
            <li>
              <a href="#">
              <i class="glyphicon glyphicon-flag"></i>
              Help </a>
            </li>
          </ul>
        </div>
        <!-- END MENU -->
      </div>
    </div>
    <div class="col-md-9">
      <div class="profile-content">         
        <div class = 'container-fluid' >
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</div>
<center>
  <strong>Powered by <a href="http://j.mp/metronictheme" target="_blank">OwnThemes</a></strong>
</center>
<br>
<br> 
    </div> 
  </body>
</html>

<script>
  var $navbar = $('#navbar');                   // Navbar to go trough!
  var $more   = $('#nav-more');                 // More More item to show/hide
  var $v_wrap = $('#navbar .nav');              // Visible wrapper
  var $h_wrap = $('#nav-more .dropdown-menu');  // Hidden wrapper
  var breaks  = [];                             // Breakpoints
  var pop_all_breakpoint = 767;                 // *** modify as needed. ***

  /**
  * Return child to it's original place in the nav-wrapper
  */
  function returnChild( $child, $dest_wrapper ) {
    var cplace = $child.attr('data-navorder'),
        inserted = false;

    // Find place for the child... insert if found...
    $dest_wrapper.children().each( function(idx, obj){
      if ( idx == cplace ) {
        $child.insertBefore(this);
        inserted = true;
      }
    });

    // ...if we didn't find a place to insert the childe, insert it last.
    if ( !inserted ) {
      $child.appendTo( $dest_wrapper );
    }
  }

  /**
  * Check navbar and handle more/show/hide.
  */
  function updateNav() {

    // If collapsed bootstrap nav, return all items to default places and hide 'more' dropdown.
    if ( $(window).width() < pop_all_breakpoint ) {
      while ( breaks.length ) {
        returnChild( $h_wrap.children().first(), $v_wrap );
        breaks.pop();
      }

      // Hide the 'more' dropdown
      $more.addClass('hidden');
      return; // Dont do anything else!
    }

    // Set/save order of menu-items (needed to keep their place among static items). Only run once!
    if ( $v_wrap.attr('data-navsetup') != 'done' ) {
      $v_wrap.children().each( function(idx, obj){
        if ( $(this).hasClass('hideable') )
          $(this).attr('data-navorder', idx);
      });
      $v_wrap.attr('data-navsetup', 'done');
    }

    // Calculate available space ( -30 to make sure )
    var availableSpace = $navbar.width() - 30 - $('.navbar-header').width();
    var changes = 0; // Could be true/false as well..

    // The visible list is overflowing the nav & we have stuff we CAN hide
    if ( availableSpace < $v_wrap.width() && $v_wrap.children('.hideable:not(.active)') ) {

      // Record the width of the list
      breaks.push( $v_wrap.width() );
      changes++;

      // Move item to the hidden list
      $v_wrap.children('.hideable:not(.active)').last().prependTo( $h_wrap );

      // Show the dropdown btn
      if ($more.hasClass('hidden')) {
        $more.removeClass('hidden');
        $h_wrap.removeClass('hidden');
      }
    }
    else { // The visible list is not overflowing

      // Is there space for another item in the nav?
      if (availableSpace > breaks[breaks.length - 1]) {

        // Move the item to the visible list
        returnChild( $h_wrap.children().first(), $v_wrap );
        breaks.pop();
        changes++;
      }

      // Hide the dropdown btn if hidden list is empty
      if ( breaks.length <= 0 ) {
        $more.addClass('hidden');
        $h_wrap.addClass('hidden');
      }
    }

    // Recur if changes were made
    if ( changes ) {
      updateNav();
    }

  }

  // Window resize listener + trigger
  $(window).resize(function() {
    updateNav();
  }).trigger('resize');

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=initMap"
                                       async defer></script>

app/views/retailers/_form.html.erb
<div class = 'form-group'>
    <%= p.label :code, 'Code' %>
    <%= p.text_field :code, :class => "form-control" %>
</div>
<div class = 'form-group'>
    <%= p.label :shop_name, 'Shop Name' %>
    <%= p.text_field :shop_name, :class => "form-control" %>
</div>
<div class = 'form-group'>
    <%= p.label :retailer_name, "Retailer Name" %>
    <%= p.text_field :retialer_name, :class => "form-control" %>    
</div>
<div class = 'form-group'>
    <%= p.label :mobile_number1, "Mobile Number 1" %>
    <%= p.text_field :mobile_number1, :class => "form-control" %>    
</div>
<div class = 'form-group'>
    <%= p.label :mobile_number2, "Mobile Number 2" %>
    <%= p.text_field :mobile_number2, :class => "form-control" %>    
</div>
<div class = 'form-group'>
    <%= p.label :address, "Address" %>
    <%= p.text_field :address, :class => "form-control" %>    
</div>
<div class = 'form-group'>
    <%= p.label :status, "Status" %>
    <%= p.text_field :status, :class => "form-control" %>    
</div>
    <%= p.submit "submit", :class => 'btn btn-success' %>

app/views/retailers/create.html.erb
<h1>Retailers#create</h1>
<p>Find me in app/views/retailers/create.html.erb</p>

app/views/retailers/edit.html.erb
<%= form_with model: @retailer, url: update_retailer_path do |p| %>
 
    <%= render partial: 'form', locals: {p: p} %>
 <% end %>

app/views/retailers/index.html.erb
<html> 
 
    <div class = "table-responsive">
        <table class='table table-striped'>
            <%= link_to "New", new_retailer_path, :class => 'btn btn-primary'  %>
            <h1>Retailers Details</h1>
            <tr>
                <th>Code</th>
                <th>Shop Name</th>
                <th>Retailer Name</th>
                <th>Mobile Number1</th>
                <th>Mobile Number2</th>
                <th>Address</th>
                <th>Status</th>
                <th></th>
            </tr>
            <% @retailers.each do |retailer| %>    
                <tr>
                    <td><%= retailer.code %></td>
                    <td><%= retailer.shop_name %></td>
                    <td><%= retailer.retialer_name %></td>
                    <td><%= retailer.mobile_number %></td>
                    <td><%= retailer.mobile_number %></td>
                    <td><%= retailer.address %></td>
                    <td><%= retailer.status %></td>   
                    <td><%= link_to "Edit", edit_retailer_path(retailer) %></td>
                </tr>    
            <% end %>
        </table>
    </div>

</html> 

app/views/retailers/new.html.erb
<%= form_with model: @retailer, url: create_retailer_path do |p| %>
    <%= render partial: 'form', locals: {p: p} %>    
 <% end %>
 

app/views/retailers/update.html.erb
<h1>Retailers#update</h1>
<p>Find me in app/views/retailers/update.html.erb</p>